# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
llm:
  api_type: "openai"  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "gpt-4o-mini" # or gpt-4-32k more powerful and expensive
  base_url: ""  # or forward url / other llm url
  api_key: "sk-"
  stream: false
#  proxy: "http://127.0.0.1:7890"  # for LLM API requests